runtime: custom
env: flex

service: default

env_variables:
  SPRING_DATASOURCE_URL: "jdbc:mysql:///sopra-db-prod?cloudSqlInstance=sopra-fs26-group-38-server:europe-west6:sopra-db&socketFactory=com.google.cloud.sql.mysql.SocketFactory&cloudSqlRefreshStrategy=lazy"
  SPRING_DATASOURCE_USERNAME: "soprauser"
  SPRING_DATASOURCE_PASSWORD: "Sopra12345!"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.MySQLDialect"
  APP_CORS_ALLOWED_ORIGINS: "https://sopra-fs26-group-38-client.vercel.app"

network:
  session_affinity: true