runtime: custom
env: flex

service: default

env_variables:
  SPRING_DATASOURCE_URL: "jdbc:mysql:///sopra-db-prod?cloudSqlInstance=sopra-fs26-group-38-server:europe-west6:sopra-db&socketFactory=com.google.cloud.sql.mysql.SocketFactory"
  SPRING_DATASOURCE_USERNAME: "soprauser"
  SPRING_DATASOURCE_PASSWORD: "IpKU^1BasC/P|x\\]"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.MySQLDialect"

network:
  session_affinity: true

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

resources:
  cpu: 1
  memory_gb: 0.6
  disk_size_gb: 10